-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-09-09 01:32:00 IST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Booking 
    ( 
     BookingId     INTEGER  NOT NULL , 
     MemberId      INTEGER  NOT NULL , 
     FacilityId    INTEGER  NOT NULL , 
     BookingDate   DATE , 
     StartTime     DATE , 
     EndTime       DATE , 
     CreatedDate   TIMESTAMP , 
     IsCancelled   INTEGER , 
     CancelledDate DATE 
    ) 
;

ALTER TABLE Booking 
    ADD CONSTRAINT Booking_PK PRIMARY KEY ( BookingId, FacilityId, MemberId ) ;

CREATE TABLE Facility 
    ( 
     FacilityId               INTEGER  NOT NULL , 
     FacilityName             VARCHAR2 (100) , 
     FacilityType             VARCHAR2 (50) , 
     Location                 VARCHAR2 (256) , 
     AddressLine_1            VARCHAR2 (200) , 
     City                     VARCHAR2 (100) , 
     Capacity                 INTEGER , 
     Description              VARCHAR2 (1000) , 
     IsActive                 NUMBER (1) , 
     Booking_BookingId        INTEGER  NOT NULL , 
     Booking_FacilityId       INTEGER  NOT NULL , 
     Booking_MemberId         INTEGER  NOT NULL , 
     FacilitySport_FacilityId INTEGER , 
     FacilitySport_SportId    INTEGER 
    ) 
;

ALTER TABLE Facility 
    ADD CONSTRAINT Facility_PK PRIMARY KEY ( FacilityId ) ;

CREATE TABLE Facility_and_Booking 
    ( 
     Facility_FacilityId INTEGER  NOT NULL , 
     Member_MemberId     INTEGER  NOT NULL 
    ) 
;

ALTER TABLE Facility_and_Booking 
    ADD CONSTRAINT Facility_and_Booking_PK PRIMARY KEY ( Facility_FacilityId, Member_MemberId ) ;

CREATE TABLE FacilitySport 
    ( 
     FacilityId INTEGER  NOT NULL , 
     SportId    INTEGER  NOT NULL 
    ) 
;

ALTER TABLE FacilitySport 
    ADD CONSTRAINT FacilitySport_PK PRIMARY KEY ( FacilityId, SportId ) ;

CREATE TABLE Inquiry 
    ( 
     InquiryId   INTEGER  NOT NULL , 
     Name        VARCHAR2 (100) , 
     Email       VARCHAR2 (256) , 
     Subject     VARCHAR2 (256) , 
     Message     VARCHAR2 (2000) , 
     InquiryDate TIMESTAMP , 
     Status      VARCHAR2 (20) 
    ) 
;

ALTER TABLE Inquiry 
    ADD CONSTRAINT Inquiry_PK PRIMARY KEY ( InquiryId ) ;

CREATE TABLE Member 
    ( 
     MemberId             INTEGER  NOT NULL , 
     FirstName            VARCHAR2 (50) , 
     LastName             VARCHAR2 (50) , 
     Email                VARCHAR2 (256) , 
     Phone                VARCHAR2 (20) , 
     AddressLine          VARCHAR2 (200) , 
     City                 VARCHAR2 (100) , 
     PasswordHash         VARCHAR2 (4000) , 
     RegisteredDate       TIMESTAMP , 
     IsActive             NUMBER (1) , 
     IsAdmin              INTEGER , 
     Booking_BookingId    INTEGER , 
     Booking_FacilityId   INTEGER , 
     Booking_MemberId     INTEGER , 
     MemberSport_MemberId INTEGER , 
     MemberSport_SportId  INTEGER 
    ) 
;

ALTER TABLE Member 
    ADD CONSTRAINT Member_PK PRIMARY KEY ( MemberId ) ;

CREATE TABLE MemberSport 
    ( 
     MemberId INTEGER  NOT NULL , 
     SportId  INTEGER  NOT NULL 
    ) 
;

ALTER TABLE MemberSport 
    ADD CONSTRAINT MemberSport_PK PRIMARY KEY ( MemberId, SportId ) ;

CREATE TABLE Review 
    ( 
     BookingId          INTEGER  NOT NULL , 
     Rating             INTEGER , 
     "Comment"          VARCHAR2 (1000) , 
     ReviewDate         TIMESTAMP , 
     Booking_BookingId  INTEGER  NOT NULL , 
     Booking_FacilityId INTEGER  NOT NULL , 
     Booking_MemberId   INTEGER  NOT NULL , 
     MemberId           INTEGER  NOT NULL 
    ) 
;
CREATE UNIQUE INDEX Review__IDX ON Review 
    ( 
     Booking_BookingId ASC , 
     Booking_FacilityId ASC , 
     Booking_MemberId ASC 
    ) 
;

ALTER TABLE Review 
    ADD CONSTRAINT Review_PK PRIMARY KEY ( BookingId ) ;

CREATE TABLE Sport 
    ( 
     SportId                  INTEGER  NOT NULL , 
     SportName                VARCHAR2 (50) , 
     MemberSport_MemberId     INTEGER , 
     MemberSport_SportId      INTEGER , 
     FacilitySport_FacilityId INTEGER , 
     FacilitySport_SportId    INTEGER 
    ) 
;

ALTER TABLE Sport 
    ADD CONSTRAINT Sport_PK PRIMARY KEY ( SportId ) ;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE Facility_and_Booking 
    ADD CONSTRAINT Facility_and_Booking_Facility_FK FOREIGN KEY 
    ( 
     Facility_FacilityId
    ) 
    REFERENCES Facility 
    ( 
     FacilityId
    ) 
;

ALTER TABLE Facility_and_Booking 
    ADD CONSTRAINT Facility_and_Booking_Member_FK FOREIGN KEY 
    ( 
     Member_MemberId
    ) 
    REFERENCES Member 
    ( 
     MemberId
    ) 
;

ALTER TABLE Facility 
    ADD CONSTRAINT Facility_Booking_FK FOREIGN KEY 
    ( 
     Booking_BookingId,
     Booking_FacilityId,
     Booking_MemberId
    ) 
    REFERENCES Booking 
    ( 
     BookingId,
     FacilityId,
     MemberId
    ) 
;

ALTER TABLE Facility 
    ADD CONSTRAINT Facility_FacilitySport_FK FOREIGN KEY 
    ( 
     FacilitySport_FacilityId,
     FacilitySport_SportId
    ) 
    REFERENCES FacilitySport 
    ( 
     FacilityId,
     SportId
    ) 
;

ALTER TABLE Member 
    ADD CONSTRAINT Member_Booking_FK FOREIGN KEY 
    ( 
     Booking_BookingId,
     Booking_FacilityId,
     Booking_MemberId
    ) 
    REFERENCES Booking 
    ( 
     BookingId,
     FacilityId,
     MemberId
    ) 
;

ALTER TABLE Member 
    ADD CONSTRAINT Member_MemberSport_FK FOREIGN KEY 
    ( 
     MemberSport_MemberId,
     MemberSport_SportId
    ) 
    REFERENCES MemberSport 
    ( 
     MemberId,
     SportId
    ) 
;

ALTER TABLE Review 
    ADD CONSTRAINT Review_Booking_FK FOREIGN KEY 
    ( 
     Booking_BookingId,
     Booking_FacilityId,
     Booking_MemberId
    ) 
    REFERENCES Booking 
    ( 
     BookingId,
     FacilityId,
     MemberId
    ) 
;

ALTER TABLE Sport 
    ADD CONSTRAINT Sport_FacilitySport_FK FOREIGN KEY 
    ( 
     FacilitySport_FacilityId,
     FacilitySport_SportId
    ) 
    REFERENCES FacilitySport 
    ( 
     FacilityId,
     SportId
    ) 
;

ALTER TABLE Sport 
    ADD CONSTRAINT Sport_MemberSport_FK FOREIGN KEY 
    ( 
     MemberSport_MemberId,
     MemberSport_SportId
    ) 
    REFERENCES MemberSport 
    ( 
     MemberId,
     SportId
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             1
-- ALTER TABLE                             18
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   1
-- WARNINGS                                 0
