-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-09-08 00:22:29 IST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE Booking 
    ( 
     BookingId   INTEGER  NOT NULL , 
     MemberId    INTEGER , 
     FacilityId  INTEGER , 
     BookingDate DATE , 
     StartTime   DATE , 
     EndTime     DATE , 
     CreatedDate TIMESTAMP 
    ) 
    LOGGING 
;

ALTER TABLE Booking 
    ADD CONSTRAINT Booking_PK PRIMARY KEY ( BookingId ) ;

CREATE TABLE Booking_and_Review 
    ( 
     Booking_BookingId INTEGER  NOT NULL , 
     Review_BookingId  INTEGER  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE Booking_and_Review 
    ADD CONSTRAINT Booking_and_Review_PK PRIMARY KEY ( Booking_BookingId, Review_BookingId ) ;

CREATE TABLE Facility 
    ( 
     FacilityId    INTEGER  NOT NULL , 
     FacilityName  VARCHAR2 (100) , 
     FacilityType  VARCHAR2 (50) , 
     Location      VARCHAR2 (256) , 
     AddressLine_1 VARCHAR2 (200) , 
     City          VARCHAR2 (100) , 
     Capacity      INTEGER , 
     Description   VARCHAR2 (1000) , 
     IsActive      NUMBER (1) 
    ) 
    LOGGING 
;

ALTER TABLE Facility 
    ADD CONSTRAINT Facility_PK PRIMARY KEY ( FacilityId ) ;

CREATE TABLE Facility_and_Booking 
    ( 
     Facility_FacilityId INTEGER  NOT NULL , 
     Member_MemberId     INTEGER  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE Facility_and_Booking 
    ADD CONSTRAINT Facility_and_Booking_PK PRIMARY KEY ( Facility_FacilityId, Member_MemberId ) ;

CREATE TABLE Facility_and_FacilitySport 
    ( 
     Facility_FacilityId      INTEGER  NOT NULL , 
     FacilitySport_FacilityId INTEGER  NOT NULL , 
     FacilitySport_SportId    INTEGER  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE Facility_and_FacilitySport 
    ADD CONSTRAINT Facility_and_FacilitySport_PK PRIMARY KEY ( Facility_FacilityId, FacilitySport_FacilityId, FacilitySport_SportId ) ;

CREATE TABLE FacilitySport 
    ( 
     FacilityId INTEGER  NOT NULL , 
     SportId    INTEGER  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE FacilitySport 
    ADD CONSTRAINT FacilitySport_PK PRIMARY KEY ( FacilityId, SportId ) ;

CREATE TABLE Inquiry 
    ( 
     InquiryId   INTEGER  NOT NULL , 
     Name        VARCHAR2 (100) , 
     Email       VARCHAR2 (256) , 
     Subject     VARCHAR2 (256) , 
     Message     VARCHAR2 (2000) , 
     InquiryDate TIMESTAMP , 
     Status      VARCHAR2 (20) 
    ) 
    LOGGING 
;

ALTER TABLE Inquiry 
    ADD CONSTRAINT Inquiry_PK PRIMARY KEY ( InquiryId ) ;

CREATE TABLE Member 
    ( 
     MemberId       INTEGER  NOT NULL , 
     FirstName      VARCHAR2 (50) , 
     LastName       VARCHAR2 (50) , 
     Email          VARCHAR2 (256) , 
     Phone          VARCHAR2 (20) , 
     AddressLine    VARCHAR2 (200) , 
     City           VARCHAR2 (100) , 
     PasswordHash   VARCHAR2 (4000) , 
     RegisteredDate TIMESTAMP , 
     IsActive       NUMBER (1) 
    ) 
    LOGGING 
;

ALTER TABLE Member 
    ADD CONSTRAINT Member_PK PRIMARY KEY ( MemberId ) ;

CREATE TABLE Member_and__Booking 
    ( 
     Member_MemberId   INTEGER  NOT NULL , 
     Booking_BookingId INTEGER  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE Member_and__Booking 
    ADD CONSTRAINT Member_and__Booking_PK PRIMARY KEY ( Member_MemberId, Booking_BookingId ) ;

CREATE TABLE Member_and_MemberSport 
    ( 
     Member_MemberId      INTEGER  NOT NULL , 
     MemberSport_MemberId INTEGER  NOT NULL , 
     MemberSport_SportId  INTEGER  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE Member_and_MemberSport 
    ADD CONSTRAINT Member_and_MemberSport_PK PRIMARY KEY ( Member_MemberId, MemberSport_MemberId, MemberSport_SportId ) ;

CREATE TABLE MemberSport 
    ( 
     MemberId INTEGER  NOT NULL , 
     SportId  INTEGER  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE MemberSport 
    ADD CONSTRAINT MemberSport_PK PRIMARY KEY ( MemberId, SportId ) ;

CREATE TABLE Review 
    ( 
     BookingId  INTEGER  NOT NULL , 
     Rating     INTEGER , 
     "Comment"  VARCHAR2 (1000) , 
     ReviewDate TIMESTAMP 
    ) 
    LOGGING 
;

ALTER TABLE Review 
    ADD CONSTRAINT Review_PK PRIMARY KEY ( BookingId ) ;

CREATE TABLE Sport 
    ( 
     SportId   INTEGER  NOT NULL , 
     SportName VARCHAR2 (50) 
    ) 
    LOGGING 
;

ALTER TABLE Sport 
    ADD CONSTRAINT Sport_PK PRIMARY KEY ( SportId ) ;

CREATE TABLE Sport_and_FacilitySport 
    ( 
     Sport_SportId            INTEGER  NOT NULL , 
     FacilitySport_FacilityId INTEGER  NOT NULL , 
     FacilitySport_SportId    INTEGER  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE Sport_and_FacilitySport 
    ADD CONSTRAINT Sport_and_FacilitySport_PK PRIMARY KEY ( Sport_SportId, FacilitySport_FacilityId, FacilitySport_SportId ) ;

CREATE TABLE Sport_and_MemberSport 
    ( 
     Sport_SportId        INTEGER  NOT NULL , 
     MemberSport_MemberId INTEGER  NOT NULL , 
     MemberSport_SportId  INTEGER  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE Sport_and_MemberSport 
    ADD CONSTRAINT Sport_and_MemberSport_PK PRIMARY KEY ( Sport_SportId, MemberSport_MemberId, MemberSport_SportId ) ;

ALTER TABLE Booking_and_Review 
    ADD CONSTRAINT Booking_and_Review_Booking_FK FOREIGN KEY 
    ( 
     Booking_BookingId
    ) 
    REFERENCES Booking 
    ( 
     BookingId
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Booking_and_Review 
    ADD CONSTRAINT Booking_and_Review_Review_FK FOREIGN KEY 
    ( 
     Review_BookingId
    ) 
    REFERENCES Review 
    ( 
     BookingId
    ) 
    NOT DEFERRABLE 
;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE Facility_and_Booking 
    ADD CONSTRAINT Facility_and_Booking_Facility_FK FOREIGN KEY 
    ( 
     Facility_FacilityId
    ) 
    REFERENCES Facility 
    ( 
     FacilityId
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Facility_and_Booking 
    ADD CONSTRAINT Facility_and_Booking_Member_FK FOREIGN KEY 
    ( 
     Member_MemberId
    ) 
    REFERENCES Member 
    ( 
     MemberId
    ) 
    NOT DEFERRABLE 
;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE Facility_and_FacilitySport 
    ADD CONSTRAINT Facility_and_FacilitySport_Facility_FK FOREIGN KEY 
    ( 
     Facility_FacilityId
    ) 
    REFERENCES Facility 
    ( 
     FacilityId
    ) 
    NOT DEFERRABLE 
;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE Facility_and_FacilitySport 
    ADD CONSTRAINT Facility_and_FacilitySport_FacilitySport_FK FOREIGN KEY 
    ( 
     FacilitySport_FacilityId,
     FacilitySport_SportId
    ) 
    REFERENCES FacilitySport 
    ( 
     FacilityId,
     SportId
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Member_and__Booking 
    ADD CONSTRAINT Member_and__Booking_Booking_FK FOREIGN KEY 
    ( 
     Booking_BookingId
    ) 
    REFERENCES Booking 
    ( 
     BookingId
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Member_and__Booking 
    ADD CONSTRAINT Member_and__Booking_Member_FK FOREIGN KEY 
    ( 
     Member_MemberId
    ) 
    REFERENCES Member 
    ( 
     MemberId
    ) 
    NOT DEFERRABLE 
;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE Member_and_MemberSport 
    ADD CONSTRAINT Member_and_MemberSport_Member_FK FOREIGN KEY 
    ( 
     Member_MemberId
    ) 
    REFERENCES Member 
    ( 
     MemberId
    ) 
    NOT DEFERRABLE 
;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE Member_and_MemberSport 
    ADD CONSTRAINT Member_and_MemberSport_MemberSport_FK FOREIGN KEY 
    ( 
     MemberSport_MemberId,
     MemberSport_SportId
    ) 
    REFERENCES MemberSport 
    ( 
     MemberId,
     SportId
    ) 
    NOT DEFERRABLE 
;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE Sport_and_FacilitySport 
    ADD CONSTRAINT Sport_and_FacilitySport_FacilitySport_FK FOREIGN KEY 
    ( 
     FacilitySport_FacilityId,
     FacilitySport_SportId
    ) 
    REFERENCES FacilitySport 
    ( 
     FacilityId,
     SportId
    ) 
    NOT DEFERRABLE 
;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE Sport_and_FacilitySport 
    ADD CONSTRAINT Sport_and_FacilitySport_Sport_FK FOREIGN KEY 
    ( 
     Sport_SportId
    ) 
    REFERENCES Sport 
    ( 
     SportId
    ) 
    NOT DEFERRABLE 
;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE Sport_and_MemberSport 
    ADD CONSTRAINT Sport_and_MemberSport_MemberSport_FK FOREIGN KEY 
    ( 
     MemberSport_MemberId,
     MemberSport_SportId
    ) 
    REFERENCES MemberSport 
    ( 
     MemberId,
     SportId
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE Sport_and_MemberSport 
    ADD CONSTRAINT Sport_and_MemberSport_Sport_FK FOREIGN KEY 
    ( 
     Sport_SportId
    ) 
    REFERENCES Sport 
    ( 
     SportId
    ) 
    NOT DEFERRABLE 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            15
-- CREATE INDEX                             0
-- ALTER TABLE                             29
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   8
-- WARNINGS                                 0
